title: Open North
description: Open North implements a collaborative local-to-global approach to improving smart cities through empirical research applied to urban problems.
logo: /theme/img/open-north-logo-header-black-en.png
language: en
baseurl:
permalink: /:year/:month/:day/:title
include: ["_pages"]
collections_dir: collections
collections:
  impacts:
  jobs:
  publications:
  webinars:
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "impacts"
    values:
      feature: false
  - scope:
      path: ""
    values:
      layout: "default"
sass:
  style: :expanded
  sass_dir: theme/_sass
  line_comments: true
plugins:
  - jekyll-redirect-from
social:
  name: Open North
  links:
    - https://twitter.com/opennorth
    - https://www.facebook.com/OpenNorth.NordOuvert
    - https://www.linkedin.com/company/open-north/
    - https://github.com/opennorth/
prose:
  metadata:
    _posts:
      - name: layout
        field:
          element: hidden
          value: post
      - name: published
        field:
          element: hidden
          value: true
      - name: title
        field:
          element: text
          label: Title
          help: All posts must have a title.
          value: ""
      - name: author
        field:
          element: text
          label: Author
          help: All posts must have an author.
          value: ""
